// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "tags": [
                    "Аккаунт"
                ],
                "summary": "Получение аккаунта аккаунта",
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/account.GetResponse200"
                        }
                    },
                    "400": {
                        "description": "Ошибка, смотри параметр error",
                        "schema": {
                            "$ref": "#/definitions/account.GetResponse400"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Аккаунт"
                ],
                "summary": "Создание аккаунта",
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/account.CreateResponse200"
                        }
                    },
                    "400": {
                        "description": "Ошибка, смотри параметр error",
                        "schema": {
                            "$ref": "#/definitions/account.CreateResponse400"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.CreateResponse200": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/repositories.Account"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "account.CreateResponse400": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "account.GetResponse200": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/repositories.Account"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "account.GetResponse400": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "repositories.Account": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "balance": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "api-key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "X API",
	Description:      "Документация для REST API игры",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
